### ISSUE TITLE
Support for hosts and tags

### ISSUE THREAD

**Issue by sgscheffler** [NathanVaughn/actions-cloudflare-purge#20]
Would be nice to support filtering hosts and tags as per API doc:

https://api.cloudflare.com/#zone-purge-files-by-cache-tags,-host-or-prefix

**Comment by NathanVaughn** [comment]
This motivated me to rewrite this from a shell script to a Python script, so this functionality has been added. Created release [v2.0.0](https://github.com/NathanVaughn/actions-cloudflare-purge/releases/tag/v2.0.0) to address this. I don't have an enterprise Cloudflare account to fully test this, but it should work per their API docs
