### ISSUE TITLE
`files` must be an array

### ISSUE THREAD

**Issue by devlsh** [NathanVaughn/actions-cloudflare-purge#31]
RE: using `urls` (internally `files`). Currently, it fails since it's passing through a string with space-delimited URLs with the following response:

```json
{
    "success": false,
    "errors": [
        {
            "code": 1014,
            "message": "\"files\", \"tags\", \"hosts\" or \"prefixes\" must be an array"
        }
    ],
    "messages": [],
    "result": null
}
```

I'm not familiar with python, but if you could split the provided URL by ` ` (space), it should work as expected for us. Thanks!

**Comment by NathanVaughn** [comment]
Interesting, I thought I had that covered but I guess not. I realized when looking at this that my argument parsing in Python was really bad, so I ended up re-writing it.

Give the `feature/proper-args` branch a try and let me know if that works:

```yaml
uses: nathanvaughn/actions-cloudflare-purge@feature/proper-args
```

I've tried it myself and it seems like things parse correctly, but for some reason my free account gets a 403 unauthorized when I try to do it:
![image](https://user-images.githubusercontent.com/8636459/177439981-1bbede74-5f38-408d-af80-5cee5d446f91.png)

As soon as I switch it back to `purge_everything: true` it works fine so not sure what's up there.

**Comment by devlsh** [comment]
Will give it a go when I'm in the office in a few hours - thanks!

iirc free accounts can't do targeted invalidations - I might be wrong though

**Comment by NathanVaughn** [comment]
That's probably it. The documentation says it's available for free accounts, but maybe it's just wrong. https://api.cloudflare.com/#zone-purge-files-by-url

**Comment by devlsh** [comment]
@NathanVaughn Seems I'm also getting a 403, and you're right that it should work on free accounts.

Running the same request in postman returns a 200 success, which is somewhat confusing.

**Comment by NathanVaughn** [comment]
I think I figured it out, I was missing a `User-Agent` header. Adding that seems to have the done the trick, let me know if that branch works now for you.

**Comment by devlsh** [comment]
That's fixed it now @NathanVaughn

**Comment by NathanVaughn** [comment]
Awesome! Thanks for testing, it's been merged.
